version: '3.8'
services:
  train:
    build: .
    command: python train_model.py
    volumes:
      - .:/app

  web:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  test:
    build: .
    command: sh -c "python wait_for_service.py && python test_model.py"
    volumes:
      - .:/app
    depends_on:
      - web
